version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:fpm
        volumes:
            - ./:/code
        networks:
            - code-network
    rabbit:
        image: "rabbitmq:3.6.6-management"
        environment:
            RABBITMQ_USE_LONGNAME: "true"
            RABBITMQ_LOGS: "/var/log/rabbitmq/rabbit.log"
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "rabbitmq"
            RABBITMQ_DEFAULT_PASS: "rabbitmq"
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
            - "15672:15672"
            - "5672:5672"
        volumes:
            -  "./rabbitmq:/var/lib/rabbitmq"
            -  "./rabbitmq/logs:/var/log/rabbitmq"
        networks:
            - code-network
networks:
    code-network:
        driver: bridge
